# This config is the base config
root: true

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"

# Typescript + Svelte support
parser: "@typescript-eslint/parser"

# Configure parsers
parserOptions:
  project:
    - ./tsconfig.json
  extraFileExtensions:
    - .svelte

plugins:
    - "@typescript-eslint"
    - svelte3

# Use others checks for Svelte
overrides:
  - processor: svelte3/svelte3
    files:
      - "**/*.svelte"

# Have Svelte linter use typescript
settings:
  svelte3/typescript: true

# Add more checks here
rules:

# Configure for the web
env:
  es6: true
  browser: true
