#!/bin/bash
read -p "PUBLIC_APP_42_ID: " PUBLIC_APP_42_ID
read -p "APP_42_SECRET: " APP_42_SECRET
read -p "PUBLIC_LOGIN_URI: " PUBLIC_LOGIN_URI
read -p "REDIRECT_URI: " REDIRECT_URI
read -p "POSTGRES_PASSWORD: " POSTGRES_PASSWORD
read -p "POSTGRES_USER: " POSTGRES_USER
read -p "POSTGRES_DB: " POSTGRES_DB
read -p "HOSTNAME: " HOSTNAME

echo -en \
"PUBLIC_APP_42_ID=$PUBLIC_APP_42_ID\n"\
"APP_42_SECRET=$APP_42_SECRET\n"\
"PUBLIC_LOGIN_URI=$PUBLIC_LOGIN_URI\n"\
"REDIRECT_URI=$REDIRECT_URI\n"\
"POSTGRES_PASSWORD=$POSTGRES_PASSWORD\n"\
"POSTGRES_USER=$POSTGRES_USER\n"\
"POSTGRES_DB=$POSTGRES_DB\n"\
"HOSTNAME=$HOSTNAME\n"\
> .env

